vich_uploader:
    db_driver: orm

    mappings:
       poster_file:
            uri_prefix: /uploads/
            upload_destination: '%kernel.project_dir%/public/uploads/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above
       poster_file_company:
         uri_prefix: /uploads/
         upload_destination: '%kernel.project_dir%/public/uploads/'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above
       poster_file_individual:
         uri_prefix: /uploads/
         upload_destination: '%kernel.project_dir%/public/uploads/'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above
